// Dependency-free HTTP + WebSocket server. Match phases, scoring and trivia awards are authoritative here.
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const triviaPool = require('./trivia-data.js');

const ROOT = __dirname;
const PORT = Number(process.env.PORT || 8000);
const MAX_PLAYERS = 12;
const PLAYER_SPAWNS = [[0,34],[0,-42],[42,0],[-42,0],[24,12],[-24,12],[24,-12],[-24,-12],[12,34],[-12,34],[12,-34],[-12,-34]];
const PHASES = [
  { phase:'battle', round:1, seconds:65 }, { phase:'trivia', round:1, seconds:30 },
  { phase:'battle', round:2, seconds:65 }, { phase:'trivia', round:2, seconds:30 },
  { phase:'battle', round:3, seconds:65 }, { phase:'trivia', round:3, seconds:30 },
  { phase:'final', round:4, seconds:70 }
];
const UPGRADE_NAMES = ['Knife','Shield','Bow','Pistol','Shotgun','Machine Gun','Speed Boost','Super Jump','Akimbo Shotguns','Rocket Launcher'];
const rooms = new Map(), clients = new Set();
const MIME = { '.html':'text/html; charset=utf-8', '.js':'text/javascript; charset=utf-8', '.css':'text/css; charset=utf-8', '.json':'application/json; charset=utf-8', '.png':'image/png', '.svg':'image/svg+xml', '.woff2':'font/woff2' };
const SAFE = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
function shuffled(a) { const out=[...a]; for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out; }
function codeForRoom() { let code; do { code=''; for(let i=0;i<4;i++) code+=SAFE[Math.floor(Math.random()*SAFE.length)]; } while(rooms.has(code)); return code; }
function send(client,value) { if(!client||client.socket.destroyed)return;const body=Buffer.from(JSON.stringify(value));let header;if(body.length<126)header=Buffer.from([0x81,body.length]);else if(body.length<=65535){header=Buffer.alloc(4);header[0]=0x81;header[1]=126;header.writeUInt16BE(body.length,2);}else{header=Buffer.alloc(10);header[0]=0x81;header[1]=127;header.writeBigUInt64BE(BigInt(body.length),2);}client.socket.write(Buffer.concat([header,body])); }
function fail(client,message){send(client,{type:'error',message});}
function publicQuestions(room){return room.questions.map(({id,question,choices,category})=>({id,question,choices,category}));}
function snapshot(room){
  const phase=room.phase==='playing'?PHASES[room.phaseIndex]?.phase||'ended':room.phase;
  return {code:room.code,host:room.host,phase,round:room.phase==='playing'?PHASES[room.phaseIndex]?.round||4:room.round||0,bots:room.bots,
    players:[...room.players.values()].map(({id,name,health,kills,deaths,score,upgradeLevel,x,z,yaw,respawn,answered})=>({id,name,health,kills,deaths,score,upgradeLevel,upgrade:UPGRADE_NAMES[upgradeLevel]||UPGRADE_NAMES[0],x,z,yaw,respawn,answered:room.phase==='playing'&&PHASES[room.phaseIndex]?.phase==='trivia'?(answered||[]):[]})),
    aiBots:(room.aiBots||[]).map(({id,name,health,kills,deaths,score,upgradeLevel,x,z,yaw,respawn})=>({id,name,health,kills,deaths,score,upgradeLevel,upgrade:UPGRADE_NAMES[upgradeLevel]||UPGRADE_NAMES[0],x,z,yaw,respawn})),
    questions:room.phase==='playing'&&PHASES[room.phaseIndex]?.phase==='trivia'?publicQuestions(room):[],
    remaining:room.phase==='playing'?Math.max(0,Math.ceil((room.phaseEndsAt-Date.now())/1000)):0};
}
function broadcast(room,value){for(const p of room.players.values())send(p.client,value);}
function update(room,type='world'){broadcast(room,{type,room:snapshot(room)});}
function lobby(room){broadcast(room,{type:'lobby',room:snapshot(room)});}
function leave(client){const room=client.room;if(!room)return;room.players.delete(client.id);client.room=null;client.id=null;if(!room.players.size){rooms.delete(room.code);return;}if(!room.players.has(room.host))room.host=room.players.keys().next().value;if(room.phase==='playing')update(room);else lobby(room);}
function join(client,room,name){if(room.players.size>=MAX_PLAYERS)return fail(client,'That room is full (12 players maximum).');if(room.phase!=='lobby')return fail(client,'That match has already started.');const id=crypto.randomUUID();client.id=id;client.room=room;if(!room.host)room.host=id;room.players.set(id,{id,name:name.slice(0,16)||'PLAYER',client,x:0,z:34,yaw:0,health:100,kills:0,deaths:0,score:0,upgradeLevel:0,respawn:0,lastState:Date.now(),lastShot:0,answered:[]});send(client,{type:'joined',id,room:snapshot(room)});lobby(room);}
function selectTrivia(room,round){const selected=room.questionDeck.slice((round-1)*3,round*3);room.questions=selected.map(q=>{const choices=shuffled(q.choices.map((text,index)=>({text,index})));return {id:q.id,question:q.question,category:q.category,choices:choices.map(c=>c.text),answer:choices.findIndex(c=>c.index===q.answer)};});for(const p of room.players.values())p.answered=[];for(const b of room.aiBots||[])for(let i=0;i<3;i++)if(Math.random()<.48)b.upgradeLevel=Math.min(9,b.upgradeLevel+1);
  // Bots participate at a modest, fixed accuracy and can only earn one step per question.
  room.botUpgradeLevels??=[0,0,0,0];room.botAnswered=selected.map((_,i)=>Array.from({length:4},()=>Math.random()<.48));
}
function beginPhase(room,index){if(index>=PHASES.length){room.phase='ended';room.phaseIndex=PHASES.length;room.phaseEndsAt=0;update(room,'ended');return;}room.phase='playing';room.phaseIndex=index;room.round=PHASES[index].round;room.phaseEndsAt=Date.now()+PHASES[index].seconds*1000;if(PHASES[index].phase==='trivia')selectTrivia(room,room.round);else room.questions=[];update(room,index===0?'start':'phase');}
function hitTest(room,shooter,yaw,pitch){const origin={x:shooter.x,y:1.4,z:shooter.z},dir={x:-Math.sin(yaw)*Math.cos(pitch),y:Math.sin(pitch),z:-Math.cos(yaw)*Math.cos(pitch)};let best=null,bestDot=.994;const targets=[...room.players.values()].filter(p=>p!==shooter).concat(room.aiBots||[]);for(const target of targets){if(target.respawn>0)continue;const dx=target.x-shooter.x,dy=1.25-origin.y,dz=target.z-shooter.z,dist=Math.hypot(dx,dy,dz),range=shooter.upgradeLevel<=1?3.2:42;if(dist>range)continue;const dot=(dx*dir.x+dy*dir.y+dz*dir.z)/dist;if(dot>bestDot){best=target;bestDot=dot;}}return best;}
function answerTrivia(client,room,player,data){const phase=PHASES[room.phaseIndex];if(room.phase!=='playing'||phase?.phase!=='trivia'||Date.now()>=room.phaseEndsAt)return fail(client,'Trivia is closed.');const qIndex=Number(data.questionIndex),choice=Number(data.choiceIndex),q=room.questions[qIndex];if(!Number.isInteger(qIndex)||!q||!Number.isInteger(choice)||choice<0||choice>=q.choices.length)return fail(client,'Invalid answer.');if(player.answered.includes(q.id))return fail(client,'You already answered this question.');player.answered.push(q.id);const correct=choice===q.answer;if(correct)player.upgradeLevel=Math.min(UPGRADE_NAMES.length-1,player.upgradeLevel+1);send(client,{type:'answerResult',questionIndex:qIndex,correct,upgradeLevel:player.upgradeLevel,upgrade:UPGRADE_NAMES[player.upgradeLevel]});update(room);}
function onMessage(client,message){let data;try{data=JSON.parse(message);}catch{return fail(client,'Invalid message.');}
  if(data.type==='create'){if(client.room)leave(client);const room={code:codeForRoom(),host:null,phase:'lobby',round:0,phaseIndex:-1,bots:true,players:new Map(),aiBots:[['BYTE',-5,25],['GLITCH',5,25],['ROOK',-6,16],['GHOST',6,16]].map(([name,x,z],i)=>({id:`bot${i}`,name,x,z,yaw:0,health:100,kills:0,deaths:0,score:0,upgradeLevel:0,respawn:0,nextShot:Date.now()+1500+i*300})),phaseEndsAt:0,questions:[]};rooms.set(room.code,room);join(client,room,String(data.name||'PLAYER').replace(/[^\w -]/g,'').trim());return;}
  if(data.type==='join'){if(client.room)leave(client);const room=rooms.get(String(data.code||'').toUpperCase());if(!room)return fail(client,'Room not found. Check the code and try again.');join(client,room,String(data.name||'PLAYER').replace(/[^\w -]/g,'').trim());return;}
  const room=client.room,player=room?.players.get(client.id);if(data.type==='leave'){leave(client);return send(client,{type:'left'});}if(!room||!player)return fail(client,'Join a room first.');
  if(data.type==='start'){if(room.host!==player.id)return fail(client,'Only the room host can start the match.');if(room.phase!=='lobby')return;if(room.players.size<1)return fail(client,'Add a player before starting.');room.questionDeck=shuffled(triviaPool).slice(0,9);[...room.players.values()].forEach((p,i)=>{p.health=100;p.kills=0;p.deaths=0;p.score=0;p.upgradeLevel=0;p.respawn=0;p.lastState=Date.now();[p.x,p.z]=PLAYER_SPAWNS[i];p.yaw=Math.atan2(p.x,p.z);p.answered=[];});room.aiBots.forEach((b,i)=>{[b.x,b.z]=[[-5,25],[5,25],[-6,16],[6,16]][i];b.health=100;b.kills=0;b.deaths=0;b.score=0;b.upgradeLevel=0;b.respawn=0;b.nextShot=Date.now()+1600+i*300;});beginPhase(room,0);return;}
  if(data.type==='answer'){answerTrivia(client,room,player,data);return;}
  const current=PHASES[room.phaseIndex]?.phase;
  if(data.type==='state'&&room.phase==='playing'&&(current==='battle'||current==='final')&&Date.now()<room.phaseEndsAt){const now=Date.now(),elapsed=Math.max(.05,(now-player.lastState)/1000),x=Number(data.x),z=Number(data.z),yaw=Number(data.yaw);if(!Number.isFinite(x)||!Number.isFinite(z)||!Number.isFinite(yaw))return;const maxTravel=Math.max(1.25,elapsed*10+.65);if(Math.hypot(x-player.x,z-player.z)>maxTravel)return;player.x=Math.max(-51,Math.min(51,x));player.z=Math.max(-51,Math.min(51,z));player.yaw=yaw;player.lastState=now;return;}
  if(data.type==='shoot'&&room.phase==='playing'&&(current==='battle'||current==='final')&&Date.now()<room.phaseEndsAt){const now=Date.now();if(now-player.lastShot<185||player.respawn>0)return;player.lastShot=now;const yaw=Number(data.yaw),pitch=Number(data.pitch)||0;if(!Number.isFinite(yaw))return;const target=hitTest(room,player,yaw,pitch);if(!target)return;const level=player.upgradeLevel;let damage=level===2?52:level===4?70:level===5?24:level===8?56:level===9?100:level<=1?55:34;if(target.upgradeLevel===1)damage*=.45;target.health=Math.max(0,target.health-damage);if(target.health===0){target.deaths++;target.respawn=2800;player.kills++;player.score+=level<=1?10:level===2?5:2;player.health=Math.min(100,player.health+10);}broadcast(room,{type:'hit',shooter:player.id,target:target.id,killed:target.health===0,room:snapshot(room)});return;}
}
function acceptSocket(req,socket){if(req.url!=='/ws'){socket.destroy();return;}const key=req.headers['sec-websocket-key'];if(!key){socket.destroy();return;}const accept=crypto.createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');socket.setNoDelay(true);const client={socket,buffer:Buffer.alloc(0),room:null,id:null};clients.add(client);socket.on('data',chunk=>{client.buffer=Buffer.concat([client.buffer,chunk]);while(client.buffer.length>=2){const b0=client.buffer[0],b1=client.buffer[1],opcode=b0&15,masked=(b1&128)!==0;let len=b1&127,offset=2;if(len===126){if(client.buffer.length<4)return;len=client.buffer.readUInt16BE(2);offset=4;}else if(len===127){if(client.buffer.length<10)return;const big=client.buffer.readBigUInt64BE(2);if(big>1048576n){socket.destroy();return;}len=Number(big);offset=10;}if(!masked||len>1048576){socket.destroy();return;}if(client.buffer.length<offset+4+len)return;const mask=client.buffer.subarray(offset,offset+4),payload=Buffer.from(client.buffer.subarray(offset+4,offset+4+len));client.buffer=client.buffer.subarray(offset+4+len);for(let i=0;i<payload.length;i++)payload[i]^=mask[i%4];if(opcode===8){socket.end();return;}if(opcode===9){socket.write(Buffer.from([0x8a,0]));continue;}if(opcode===1)onMessage(client,payload.toString('utf8'));}});socket.on('close',()=>{clients.delete(client);leave(client);});socket.on('error',()=>{clients.delete(client);leave(client);});}
const server=http.createServer((req,res)=>{if(req.url==='/healthz'){res.writeHead(200,{'content-type':'text/plain'});return res.end('ok');}let pathname;try{pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);}catch{res.writeHead(400);return res.end('Bad request');}if(pathname==='/')pathname='/index.html';const file=path.resolve(ROOT,'.'+pathname);if(!file.startsWith(ROOT+path.sep)){res.writeHead(403);return res.end('Forbidden');}fs.readFile(file,(err,body)=>{if(err){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'content-type':MIME[path.extname(file)]||'application/octet-stream','cache-control':'no-cache'});res.end(body);});});
server.on('upgrade',acceptSocket);
setInterval(()=>{const now=Date.now();for(const room of rooms.values()){if(room.phase!=='playing')continue;const phase=PHASES[room.phaseIndex]?.phase;if(phase==='battle'||phase==='final'){
    for(const p of room.players.values())if(p.respawn>0){p.respawn=Math.max(0,p.respawn-100);if(!p.respawn){const spawns=[[-23,0],[23,0],[0,-23],[0,23],[0,34]];const s=spawns[Math.floor(Math.random()*spawns.length)];p.x=s[0];p.z=s[1];p.health=100;}}
    for(const b of room.aiBots||[]){if(b.respawn>0){b.respawn=Math.max(0,b.respawn-100);if(!b.respawn){const spawns=[[-5,25],[5,25],[-6,16],[6,16]];[b.x,b.z]=spawns[Math.floor(Math.random()*spawns.length)];b.health=100;}continue;}
      const target=[...room.players.values()].filter(p=>p.respawn<=0).sort((a,c)=>Math.hypot(a.x-b.x,a.z-b.z)-Math.hypot(c.x-b.x,c.z-b.z))[0];if(!target)continue;const dx=target.x-b.x,dz=target.z-b.z,dist=Math.hypot(dx,dz)||1;b.yaw=Math.atan2(-dx,-dz);if(dist>4.5){b.x=Math.max(-47,Math.min(47,b.x+dx/dist*.22));b.z=Math.max(-47,Math.min(47,b.z+dz/dist*.22));}if(dist<25&&b.nextShot<=now){b.nextShot=now+1800+Math.random()*1100;if(Math.random()<Math.max(.16,.44-dist*.01)){target.health=Math.max(0,target.health-(8+Math.random()*8));if(!target.health){target.deaths++;target.respawn=2800;b.kills++;b.score+=b.upgradeLevel<=1?10:b.upgradeLevel===2?5:2;}}}
    }
  }if(now>=room.phaseEndsAt){beginPhase(room,room.phaseIndex+1);continue;}update(room,'world');}},100);
setInterval(()=>{for(const client of clients)if(!client.socket.destroyed)client.socket.write(Buffer.from([0x89,0]));},25000).unref();
server.listen(PORT,'0.0.0.0',()=>console.log(`FRAG ROOM listening on ${PORT}; ${triviaPool.length} trivia questions loaded`));
