// Shared, intentionally varied questions used by the browser client and room server.
(function (root) {
  const questions = [
    ['Which planet has the shortest day?', ['Jupiter','Mars','Mercury','Venus'], 0, 'Space'],
    ['What is the chemical symbol for gold?', ['Ag','Au','Gd','Go'], 1, 'Science'],
    ['Which ocean is the largest?', ['Atlantic','Indian','Arctic','Pacific'], 3, 'Geography'],
    ['Who wrote “The Hobbit”?', ['C. S. Lewis','J. R. R. Tolkien','Ursula Le Guin','Terry Pratchett'], 1, 'Books'],
    ['What is the capital of Canada?', ['Toronto','Vancouver','Ottawa','Montreal'], 2, 'Geography'],
    ['How many sides does a hexagon have?', ['Five','Six','Seven','Eight'], 1, 'Math'],
    ['Which animal is the largest living mammal?', ['African elephant','Blue whale','Giraffe','Whale shark'], 1, 'Nature'],
    ['What gas do plants absorb from the air?', ['Oxygen','Nitrogen','Carbon dioxide','Hydrogen'], 2, 'Science'],
    ['In which country did the Olympic Games originate?', ['Italy','Greece','Egypt','Turkey'], 1, 'History'],
    ['What is the hardest natural substance?', ['Quartz','Diamond','Granite','Topaz'], 1, 'Science'],
    ['Which instrument has 88 keys on a standard version?', ['Violin','Piano','Harp','Accordion'], 1, 'Music'],
    ['What is the smallest prime number?', ['0','1','2','3'], 2, 'Math'],
    ['Which country is home to the city of Kyoto?', ['China','South Korea','Japan','Thailand'], 2, 'Geography'],
    ['What is the main language spoken in Brazil?', ['Spanish','Portuguese','French','Italian'], 1, 'Language'],
    ['Which blood cells help carry oxygen?', ['Platelets','Red blood cells','White blood cells','Stem cells'], 1, 'Science'],
    ['How many players from one team are on court in basketball?', ['Four','Five','Six','Seven'], 1, 'Sports'],
    ['Which artist painted the ceiling of the Sistine Chapel?', ['Raphael','Leonardo da Vinci','Michelangelo','Donatello'], 2, 'Art'],
    ['What is the closest star to Earth?', ['Proxima Centauri','The Sun','Sirius','Vega'], 1, 'Space'],
    ['Which metal is liquid at typical room temperature?', ['Tin','Mercury','Aluminum','Copper'], 1, 'Science'],
    ['What is the largest hot desert on Earth?', ['Gobi','Sahara','Arabian','Kalahari'], 1, 'Geography'],
    ['Which board game uses the pieces called bishops and rooks?', ['Checkers','Chess','Backgammon','Go'], 1, 'Games'],
    ['What is the square root of 144?', ['10','11','12','14'], 2, 'Math'],
    ['Which bird is famous for mimicking human speech?', ['Ostrich','Parrot','Penguin','Albatross'], 1, 'Nature'],
    ['What is the freezing point of water in Celsius?', ['0°','10°','32°','100°'], 0, 'Science'],
    ['Which continent contains the Amazon rainforest?', ['Africa','Asia','South America','Australia'], 2, 'Geography'],
    ['Who was the first person to walk on the Moon?', ['Buzz Aldrin','Yuri Gagarin','Neil Armstrong','John Glenn'], 2, 'History'],
    ['Which food is traditionally the main ingredient in hummus?', ['Lentils','Chickpeas','Peas','Soybeans'], 1, 'Food'],
    ['What does “WWW” stand for in a web address?', ['World Wide Web','Web World Wire','Wide World Window','World Web Watch'], 0, 'Technology'],
    ['Which organ pumps blood around the human body?', ['Lung','Liver','Heart','Kidney'], 2, 'Science'],
    ['Which US state is nicknamed the Sunshine State?', ['California','Florida','Arizona','Hawaii'], 1, 'Geography'],
    ['What is the name of the toy cowboy in Toy Story?', ['Jessie','Woody','Andy','Bullseye'], 1, 'Film'],
    ['Which shape has exactly three sides?', ['Pentagon','Triangle','Trapezoid','Rhombus'], 1, 'Math'],
    ['What is the largest species of shark?', ['Great white','Tiger shark','Whale shark','Hammerhead'], 2, 'Nature'],
    ['Which planet is known for its prominent rings?', ['Saturn','Neptune','Earth','Mars'], 0, 'Space'],
    ['In which sport would you perform a slam dunk?', ['Volleyball','Basketball','Tennis','Handball'], 1, 'Sports'],
    ['What is the currency of the United Kingdom?', ['Euro','Pound sterling','Franc','Krone'], 1, 'Geography'],
    ['Which material is made from the flax plant?', ['Cotton','Linen','Wool','Silk'], 1, 'Craft'],
    ['How many minutes are in two and a half hours?', ['120','135','150','180'], 2, 'Math'],
    ['Which ocean lies between Africa and Australia?', ['Pacific','Atlantic','Indian','Southern'], 2, 'Geography'],
    ['What is the name of the force that pulls objects toward Earth?', ['Friction','Magnetism','Gravity','Inertia'], 2, 'Science'],
    ['Which composer wrote the Four Seasons?', ['Mozart','Vivaldi','Bach','Beethoven'], 1, 'Music'],
    ['What do bees collect from flowers to make honey?', ['Nectar','Sap','Pollen only','Dew'], 0, 'Nature'],
    ['Which ancient civilization built Machu Picchu?', ['Maya','Inca','Aztec','Olmec'], 1, 'History'],
    ['What is the longest bone in the human body?', ['Tibia','Humerus','Femur','Fibula'], 2, 'Science'],
    ['Which punctuation mark ends a direct question?', ['Comma','Colon','Question mark','Semicolon'], 2, 'Language'],
    ['What is the name of the galaxy that contains our Solar System?', ['Andromeda','Milky Way','Whirlpool','Sombrero'], 1, 'Space'],
    ['Which country gifted the Statue of Liberty to the United States?', ['France','Spain','Canada','Portugal'], 0, 'History'],
    ['What is the process called when liquid water becomes vapor?', ['Condensation','Freezing','Evaporation','Melting'], 2, 'Science'],
    ['Which chess piece can move in an L shape?', ['Bishop','Knight','Queen','Pawn'], 1, 'Games'],
    ['What is the largest internal organ in the human body?', ['Brain','Liver','Lung','Stomach'], 1, 'Science'],
    ['Which planet is known as the Red Planet?', ['Venus','Mars','Mercury','Uranus'], 1, 'Space'],
    ['What is the first element on the periodic table?', ['Helium','Oxygen','Hydrogen','Carbon'], 2, 'Science'],
    ['Which country has a maple leaf on its national flag?', ['Denmark','Canada','Austria','Switzerland'], 1, 'Geography'],
    ['In music, how many notes are in a standard major scale?', ['Five','Six','Seven','Eight'], 2, 'Music'],
    ['What is a young frog called?', ['Calf','Tadpole','Nymph','Fry'], 1, 'Nature']
  ].map(([question, choices, answer, category], id) => ({ id, question, choices, answer, category }));

  if (typeof module !== 'undefined' && module.exports) module.exports = questions;
  root.FRAG_TRIVIA = questions;
})(typeof globalThis !== 'undefined' ? globalThis : window);
